### ISSUE TITLE
Can't flash .hex file on Arduino Leonardo

### ISSUE THREAD

**Issue by ghost** [t2t-sonbui/ArduinoHexUploadExample#1]
Hi, I need to be able to flash a .hex on an Arduino Leonardo through an Android tablet in a custom application. This library seems perfect, but I have some issues to get it working.
I've tried your example before implementing the library in my app, I've put my .hex file in the assets folder and changed the file name in the program, then I also changed the board in the uploadHex() method to ARDUINO_LEONARD.
However it doesn't work, it sees the Arduino on /dev/bus/usb/001/014 after pressing "usb request" but then when pressing the green button to flash the Arduino it keeps saying "Port still present" and then it crashes.
I've tried to take a look at the code but I don't really understand what happens in the Close() method of Avr109BootloaderProgrammer.java.
Here is the full log (https://pastebin.com/F3xcgHL3) after pressing the green button, it would be great if you could help me!

**Comment by ghost** [comment]
Hello again t2t-sonbui, I don't know if you or anyone else will ever read this but I wanted to update this issue. 
First of all, I made a mistake in the configuration of the Arduino board since the example was a UNO and I didn't know that I had to specify additional parameters for the Leonardo, in particular the reset behaviour. 
However, it didn't solve the problem because after executing the reset behaviour the program would keep saying "Port not found", even though the port was present. 
So I spent some day digging through your code and I realized that your library simply doesn't work with devices that require a 1200bps reset before flashing the hex file. As a matter of fact, even your complete application from the Play Store "Arduino Hex Uploader-Firmware Bin Upload" doesn't work with these devices. 
Instead, the ArduinoSketchUploader .net library works perfectly on Windows, maybe your porting has some issues on Android.
Nevertheless, I needed to make it work so I made a custom reset behaviour simply by using the "tryGetDevice" method of the UsbSerialManager class with a 1200bps baud rate. 
Then, after resolving some issues with the usb permissions on the ports (because they are different for the reset and for the actual flashing, for example the reset happens on the /dev/bus/usb/001/014 and the flashing on the /dev/bus/usb/001/015, so it's necessary to request permissions for both of them) I managed to get it working every time without any issues!
I won't close the issue because it's still present both in the example and the complete application, it's weird that none has ever reported this but I think you should look into it.

**Comment by t2t-sonbui** [comment]
Hi
Have you solved this problem yet?
Also test it out with a pure Java app.
https://github.com/t2t-sonbui/Java-ArduinoSketchUploader/blob/master/ArduinoSketchUploader/src/Test/Test.java
I made this project for android in a hurry as a template for android because many people need it. I'll spend some time testing it later, right now I'm pretty busy, any pull is welcome

**Comment by ghost** [comment]
Hi, thank you for answering.

Yes, I managed to solve the problem by writing some code to open and close the serial port with a 1200bps baud rate in the main of my app, waiting for 1.5 seconds and then calling the upload method.
Instead, the reset method of the library would get stuck waiting for the serial port to disappear and then timeout after 10 seconds. 
It's definitely not an elegant and proper solution, since I even commented some code in your library, but in my case it's good enough.
Therefore, the issue still exists both in the library and in the application on the Play Store, so when you have time try to look into it. As said, it happens only with chips that need a 1200bps reset behaviour, or at least that's what I tested since I only have Leonardos. 

Nonetheless, the rest of the code works perfectly and it solved me a big issue, so thanks a lot!
